you: view://webcam
chris:
  - http://yourethebest.s3.amazonaws.com/54e6aba0c9b861087f030d23ae1b4c0a92ecfa15.jpg
erica: https://s3-eu-west-1.amazonaws.com/yourethebest/dd39f9824b2b6a9fc974a4441df76c90882d6f1f.jpg